name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a crash! Please fill out as much detail as possible.

  - type: textarea
    id: reNut or reNut-Launcher
    attributes:
      label: Description
      description: Was it reNut or reNut-Launcher?
      placeholder: Was it reNut or reNut-Launcher?
    validations:
      required: true

  - type: textarea
    id: if reNut 
    attributes:
      label: What World and What action was happening when the crash occured
      description: if renut
      placeholder: if reNut-Launcher please fill space with N/A
    validations:
      required: true

   - type: textarea
    id: if reNut-Launcher
    attributes:
      label: was happening when the crash occured
      description: if reNut-Launcher
      placeholder: if reNut please fill space with N/A
    validations:
      required: true
