[[midasm_hook]]
address = 0x825A9110
name = "overworld_vehicles_hook"
registers = []
after_instruction = false
jump_address_on_true = 0x825A8F24

[[midasm_hook]]
address = 0x824CE324
name = "no_notes_spent"
registers = []
after_instruction = false
jump_address_on_true = 0x824CE32C

[[midasm_hook]]
address = 0x8228A850                   
name = "fps_hook"
registers = ["r11"]
after_instruction = true

[[midasm_hook]]
address = 0x821F8CC4
name = "fpsCount_hook"
registers = []
after_instruction = false

[[midasm_hook]]
address = 0x823ED858
name = "meGetResolutionParams_hook"
registers = ["r5", "r6"]
after_instruction = true
jump_address_on_true = 0x823ED950

[[midasm_hook]]
address = 0x8228F610
name = "Optimization_Hook"
registers = []
after_instruction = false

[[midasm_hook]]
address = 0x82b680f8
name = "disable_lod"
registers = []
after_instruction = false
jump_address_on_true = 0x82B68110


[[midasm_hook]]
address = 0x82278380
name = "Infinite_fuel_and_ammo"
registers = []
after_instruction = false
return = true

[[midasm_hook]]
address = 0x822C7F0C
name = "StopNSwap_hook"
registers = ["r22"]
after_instruction = true

[[midasm_hook]]
address = 0x823F47C8
name = "Infinite_health"
registers = []
after_instruction = false
jump_address_on_true = 0x823F47D0

[[midasm_hook]]
address = 0x82526200
name = "No_Timer"
registers = []
after_instruction = false
jump_address_on_true = 0x8252620C

[[midasm_hook]]
address = 0x8251DD10
name = "Infinite_parts"
registers = ["r10"]
after_instruction = false

[[midasm_hook]]
address = 0x8264AC14
name = "Extended_build_range"
registers = []
after_instruction = false
jump_address_on_true = 0x8264AE28

[[midasm_hook]]
address = 0x8251CA9C
name = "BanjoActorOverride"
registers = ["r3", "r5"]
after_instruction = true
jump_address_on_false = 0x8251CABC