[functions]
0x8264DF28 = { name = "Direct3D_CreateDevice" }
0x822812C8 = { name = "D3DDevice_Clear" }
0x82287590 = { name = "D3DDevice_Swap" }
0x8264E118 = { name = "D3DDevice_ReleaseThreadOwnership" }
0x8264D948 = { name = "D3DDevice_SetGammaRamp" }
0x82657508 = { name = "D3DDevice_SetRingBufferParameters" }
0x82220B20 = { name = "D3DDevice_SetShaderGPRAllocation" }
0x82657488 = { name = "D3DDevice_BlockUntilIdle" }
0x82658988 = { name = "D3DDevice_SetScreenExtentQueryMode" }
0x8222C7A0 = { name = "D3DDevice_DrawVertices" }
0x8222E520 = { name = "D3DDevice_DrawVerticesUP" }
0x826567C8 = { name = "D3DDevice_DrawIndexedVertices" }
0x8222CC50 = { name = "D3DDevice_BeginVertices" }
0x8222D6C8 = { name = "D3DDevice_Resolve" }
0x822788A0 = { name = "D3DDevice_BeginTiling" }
0x82212328 = { name = "D3DDevice_EndTiling" }
0x82655FE8 = { name = "D3DDevice_CreateSurface" }
0x82655EC8 = { name = "D3DDevice_CreateTexture" }
0x82654DB8 = { name = "D3DDevice_CreateVertexBuffer" }
0x82654EE0 = { name = "D3DDevice_CreateIndexBuffer" }
0x82654e80 = { name = "D3DVertexBuffer_Lock" }
0x82654f90 = { name = "D3DIndexBuffer_Lock" }
0x82654ed0 = { name = "D3DVertexBuffer_Unlock" }
0x82656150 = { name = "D3DSurface_LockRect" }
0x82655ea8 = { name = "D3DLineTexture_LockRect" }
0x82208720 = { name = "D3DResource_Release" }
0x822088B0 = { name = "D3DResource_AddRef" }
0x822084F0 = { name = "D3DResource_Destroy" }
0x82208110 = { name = "D3DResource_GetType" }
0x8264EA90 = { name = "D3DDevice_CreateVertexDeclaration" }
0x8264E8B0 = { name = "D3DDevice_CreateVertexShader" }
0x8264E6A8 = { name = "D3DDevice_CreatePixelShader" }


